name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build-main_downsample
      run: |
        g++ -std=c++17 -O2 main_downsample.cpp && ./a.out
    - name: build-main
      run: |
        g++ -std=c++17 -O2 main.cpp && ./a.out